--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonwynn10/LuckPerms
build-by-default: true
projects:
  LuckPerms:
    path: ""
    icon: "icon.png"
    lint: false
    excludeDirs:
      - tests
      - .github
      - build
      - tools
    excludeFiles:
      - .gitignore
      - CONTRIBUTING.md
      - SECURITY.md
    libs:
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
      - src: poggit/libasynql/libasynql
        version: ^4.0.1
      - src: sof3/await-generator/await-generator
        version: ^3.1.0
...
