name: LuckPerms
main: jasonw4331\LuckPerms\LuckPerms
src-namespace-prefix: jasonw4331\LuckPerms
version: 1.0.0
api: [5.0.0]
load: STARTUP
author: jasonw4331
description: A permissions plugin for PocketMine-MP servers based on lucko/LuckPerms
website: https://luckperms.net