name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: PHPStan analysis
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.1.17"
        pm-version-major: [ 4 ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: pmmp/setup-php-action@589cc43fddede20c8b0469828431d747fb1a1145
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          pm-version-major: ${{ matrix.pm-version-major }}

      - name: Restore Composer package cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install PHPStan Composer dependencies
        working-directory: ./tools/phpstan
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        working-directory: ./tools/phpstan
        run: vendor/bin/phpstan analyze -c ./phpstan.neon.dist
  codestyle:
    name: Code Style checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: php-cs-fixer:3.11

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff --config=./tools/cs-fixer/.php-cs-fixer.php
